# Setup
title:               Korean
tagline:             'learning by typing'
description:         'A DC <a href="https://github.com/MiaHub/Korean" target="_blank">inspiration</a>'
url:                 "https://miahub.github.io/Korean/"
baseurl:             ""
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              DC
  url:               "https://miahub.github.io/Korean/" 
  email:             dietercho@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y